language: android
jdk:
  - oraclejdk8

env:
  global:
    - secure: "Jn3NfxvugxDia/QdsR+dh0exk6K+rVEL3OujxGnp6EkWtuxDCHZbHgOnhcbZDf3igmFxcE8q11WdmOxleT0iy/6lnGRMvfrC4dLeB9rhK9MSZ4S/pyyxT+ncTVErKNhYjaTmOYXN6FZIOCsKscXD5+tNK1rzChdHzO40NtXy3SzbOagdLA0yCGwHh8S2emiA7TmPSL0GBoN9ag5GG0NWn0V+/0pYHbIztOzmSavHTd9SUEAm321QK0C3ZxhMFRBbSpGCQIBmpfezerwTW7LFjAMBDEG4SefyIFndJ0LcxLcH6lAFFE/oSMpHOOV7XScEpm7as78i83Ggd04ZkIAZtKCVeaZOQf/bACpWaQFRqXReCHADkDo5NRPbalXyy8MaaOP3Pk86ejQFhygSOiQqT6/LkAmQ4RtYow95IxsiWtLjx0iGY/5nOMdZJrUqspDnhInxruPbfHVwFddp/t6LsSqte8B+G2fRc6rHMbj69HpVDOImtj/Q22DDm4AGP075dXZN+WF7+WYfKdbvW0GqDCo4bjlkHkZ8T779xpiZk6uY3A0/wIXNqLLVibVHp2zDu0RYYpiRzW+puLg3hY6KyjuB9utXQ0NaDQgK7ta0KSlJedlZex4+Z7u8zcr5NEWMJjTCbRLPuON18rjBLT9dS9wjdCrcRBVyr7HjHbY3H78="

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository

sudo: required

before_script:
    - sudo service postgresql stop || true
    - sudo service mysql stop || true
    - sudo service memcached stop || true
    - sudo service bootlogd stop || true
    - sudo service elasticsearch stop || true
    - sudo service mongodb stop || true
    - sudo service neo4j stop || true
    - sudo service cassandra stop || true
    - sudo service riak stop || true
    - sudo service rsync stop || true
    - sudo service x11-common stop || true

script:
    - ./gradlew clean assembleDebug -PdisablePreDex
    - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./gradlew uploadDeployGateDebug; fi
cache:
  directories:
    - $HOME/.gradle/wrapper/

